### PR TITLE
replace cover with useClickOutside hook

### LINKED ISSUE #503: Moderation Dialog: Scrolling on modal doesn't work
reported by @liamegan 

> Moderation dialogue is broken, when opening the reason a scrollbar appears but you can't scroll.

### PR DESCRIPTION
**Pull request by maerzhase**
- fix #503 

We are using a `<Cover />` component when select is open that handles closing the open select dialog when you click anywhere. Since the `<Cover />` lays ontop of the scrollable area the scroll event doesn't arrive in the scrollable container. 

I removed the `Cover` from the `Select` component and replaced it with the `clickOutsideHook`

### CODE REVIEW

File: src/components/Input/Select.tsx [hunk 1]
```diff
@@ -115,6 +115,8 @@ export function Select({
   // what are the options displayed ?
   const displayOptions = searchResults || options
 
+  useClickOutside(selectRef, () => setOpened(false), false)
```
Comment (GemN) [inline src/components/Input/Select.tsx:118]: Skip "useClickOutside" when options are not displayed

**Review by GemN — CHANGES_REQUESTED** [review]

**Review by GemN — APPROVED** [review]
