### PR TITLE
Fix/#369 add article related actions

### LINKED ISSUE #369: [Articles] Add article-related actions
* base branch: `dev`

Some actions are missing from the activity.

```
ARTICLE_MINTED                = "ARTICLE_MINTED",
  ARTICLE_METADATA_UPDATED      = "ARTICLE_METADATA_UPDATED",
  ARTICLE_METADATA_LOCKED       = "ARTICLE_METADATA_LOCKED",
  ARTICLE_EDITIONS_TRANSFERED   = "ARTICLE_EDITIONS_TRANSFERED",
```

They need to be added 
image

I'll run over the wording don't bother much.

### PR DESCRIPTION
**Pull request by maerzhase**
- fix #369 

This PR adds the the components for article related actions

@ciphrd for the article metadata updated I added the revisions to the infos. this way we can render the updates more verbose. LMKWYT

Screenshot 2022-09-07 at 18 42 37

### CODE REVIEW

File: src/components/Activity/Activity.tsx [hunk 1]
```diff
@@ -32,6 +32,10 @@ const ActionsPredecescence: Record<TokenActionType, number> = {
   AUCTION_BID                   : 4,
   AUCTION_CANCELLED             : 4,
   AUCTION_FULFILLED             : 4,
+  ARTICLE_MINTED                : 0,
+  ARTICLE_EDITIONS_TRANSFERED   : 1,
+  ARTICLE_METADATA_UPDATED      : 1,
+  ARTICLE_METADATA_LOCKED       : 20,
```
Comment (maerzhase) [inline src/components/Activity/Activity.tsx:38]: @ciphrd wasn't 100% sure about this one.

Comment (ciphrd) [reply src/components/Activity/Activity.tsx:38]: I think it's obsolete now I'll take a deeper look later, not sure

**Review by ciphrd — APPROVED** [review]
LGTM

I also made a refacto cause it was getting messy in there ahah
