### PR TITLE
fix(article): invalid slug with just a dot redirect to id

### LINKED ISSUE #364: [Articles] Some slugs cannot be set in the url
* base branch: `dev`

Can be tested on article id 321

The article title is `𝗔𝗡𝗔𝗩𝗘𝗥.𝗦𝗘` which was sluggified to `.` because of unsupported characters. However, the "." cannot be used next to a "/" in the url as it is removed by the browser:

`https://fxhash.xyz/article/./` is turned into `https://fxhash.xyz/article`

# Resolution

* detect edge cases where all the sug characters cannot be added to the url
* use the ID url instead

Function to update: `getArticleUrl`

### PR DESCRIPTION
**Pull request by GemN**
fix #364

### CODE REVIEW

File: src/utils/entities/articles.ts [hunk 1]
```diff
@@ -8,11 +8,15 @@ const flagged: ArticleFlag[] = [
...
     : `/article/id/${article.id}`
 }
 
 export function isArticleFlagged(article: NFTArticleInfos): boolean {
   return flagged.includes(article.flag)
-}
\ No newline at end of file
+}
+
+export function isValidSlug(slug: string): boolean {
```
Comment (ciphrd) [inline src/utils/entities/articles.ts:20]: The rule can be extended to "is valid if it doesn't contain a slug".
There are a few other iterations of slugs not being valid when they contain a dot.

**Review by ciphrd — CHANGES_REQUESTED** [review]
